import type { Listing } from "./types"

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    title: "Modern Warehouse Space",
    location: "Denver, CO 80205",
    price: 2750,
    size: 2200,
    type: "Warehouse",
    availability: "Immediate",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "great",
    features: ["dock-high", "office", "hvac"],
    description: "Modern warehouse space with dock-high loading and office area.",
  },
  {
    id: "listing-2",
    title: "Industrial Workshop",
    location: "Aurora, CO 80011",
    price: 3200,
    size: 2800,
    type: "Industrial",
    availability: "30 Days",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "fair",
    features: ["drive-in", "power", "clear-height"],
    description: "Spacious industrial workshop with high ceilings and heavy power.",
  },
  {
    id: "listing-3",
    title: "Small Shop Space",
    location: "Lakewood, CO 80214",
    price: 1850,
    size: 1200,
    type: "Shop",
    availability: "Immediate",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "great",
    features: ["drive-in", "restroom", "parking"],
    description: "Perfect small shop space for trades or light manufacturing.",
  },
  {
    id: "listing-4",
    title: "Mixed-Use Commercial Unit",
    location: "Denver, CO 80216",
    price: 4500,
    size: 3500,
    type: "Mixed-Use",
    availability: "60 Days",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "over-market",
    features: ["office", "hvac", "parking", "restroom"],
    description: "Versatile mixed-use space with retail frontage and warehouse in back.",
  },
  {
    id: "listing-5",
    title: "Flex Industrial Space",
    location: "Englewood, CO 80112",
    price: 3800,
    size: 3000,
    type: "Industrial",
    availability: "30 Days",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "fair",
    features: ["dock-high", "drive-in", "office", "hvac"],
    description: "Flexible industrial space with both dock-high and drive-in access.",
  },
  {
    id: "listing-6",
    title: "Small Warehouse Unit",
    location: "Commerce City, CO 80022",
    price: 2100,
    size: 1800,
    type: "Warehouse",
    availability: "Immediate",
    imageUrl: "/placeholder.svg?height=400&width=600",
    dealScore: "great",
    features: ["drive-in", "clear-height", "power"],
    description: "Affordable warehouse unit with 18' clear height and drive-in door.",
  },
]
