-- Insert sample properties with Cloudinary integration
INSERT INTO lss_properties (
    title,
    description,
    address,
    city,
    state,
    zip_code,
    property_type,
    size_sqft,
    price_monthly,
    lease_type,
    available_date,
    features,
    images,
    primary_image,
    deal_score,
    is_active
) VALUES 
(
    '1,200 sq ft Flex Space Units',
    'Modern flex space units with ample parking and convenient access to major highways. Perfect for small businesses looking for flexible commercial space.',
    '11450 N Cherokee St',
    'Northglenn',
    'CO',
    '80234',
    'Flex Space',
    1200,
    2850.00,
    'NNN',
    CURRENT_DATE,
    '["Ample parking", "Highway access", "Modern facilities", "Flexible layout"]',
    '["11450-n-cherokee-st-northglenn_waxxrp"]',
    '11450-n-cherokee-st-northglenn_waxxrp',
    'good',
    true
),
(
    '4,800 sq ft Flex Facility',
    'Aerial view of modern flex facility with heavy power capabilities and kitchenette. Ideal for light manufacturing or distribution operations.',
    'Boulder Industrial Park',
    'Boulder',
    'CO',
    '80301',
    'Flex Space',
    4800,
    4500.00,
    'NNN',
    CURRENT_DATE,
    '["12 ft driving door", "Heavy power", "Kitchenette", "High ceilings"]',
    '["boulder-aerial-facility_is0jfl"]',
    'boulder-aerial-facility_is0jfl',
    'great',
    true
),
(
    '1,850 sq ft Warehouse',
    'Industrial warehouse space with driving door access and heavy electrical service. Perfect for storage, light manufacturing, or distribution.',
    '1234 Industrial Blvd',
    'Lakewood',
    'CO',
    '80215',
    'Industrial Warehouse',
    1850,
    3000.00,
    'NNN',
    CURRENT_DATE,
    '["Driving door", "200 amps 3p power", "Outdoor storage", "16 ft clear height"]',
    '["lakewood-warehouse_prqnva"]',
    'lakewood-warehouse_prqnva',
    'excellent',
    true
),
(
    'Retail Storefront',
    'Prime retail location with street visibility and foot traffic. Perfect for retail businesses looking for high-visibility commercial space.',
    'Centennial Retail Center',
    'Centennial',
    'CO',
    '80112',
    'Retail',
    2200,
    3900.00,
    'NNN',
    CURRENT_DATE,
    '["Street visibility", "Foot traffic", "Parking", "Storefront windows"]',
    '["retail-centennial_ltacwi"]',
    'retail-centennial_ltacwi',
    'good',
    true
),
(
    'Industrial Unit',
    'Flexible industrial space with front office and warehouse area. Ideal for businesses needing both office and storage space.',
    'Brighton Industrial Park',
    'Brighton',
    'CO',
    '80601',
    'Industrial',
    1800,
    2200.00,
    'NNN',
    CURRENT_DATE,
    '["Front office", "Warehouse back", "Parking", "Loading dock"]',
    '["brighton-flex-space_rfhfnv"]',
    'brighton-flex-space_rfhfnv',
    'great',
    true
),
(
    'Flex Space',
    'Large flex space with ample parking and drive-in access. Perfect for businesses requiring significant space and vehicle access.',
    'Broomfield Business Park',
    'Broomfield',
    'CO',
    '80021',
    'Flex Space',
    5500,
    6500.00,
    'NNN',
    CURRENT_DATE + INTERVAL '30 days',
    '["Ample Parking", "Drive-In (2x)", "Heavy Power", "High ceilings"]',
    '["broomfield-flex-space_fzp3v2"]',
    'broomfield-flex-space_fzp3v2',
    'good',
    true
);

-- Create a view for active properties
CREATE OR REPLACE VIEW lss_active_properties AS
SELECT 
    id,
    title,
    description,
    address,
    city,
    state,
    zip_code,
    property_type,
    size_sqft,
    price_monthly,
    lease_type,
    available_date,
    features,
    images,
    primary_image,
    deal_score,
    created_at
FROM lss_properties 
WHERE is_active = true 
ORDER BY created_at DESC;